"""add media_links

Revision ID: 122d7b0e1feb
Revises: a23c7b701fb7
Create Date: 2018-09-19 21:34:52.110346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122d7b0e1feb'
down_revision = 'a23c7b701fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('media_links', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'media_links')
    # ### end Alembic commands ###
