"""cached path

Revision ID: 245d116b8a06
Revises: f128dd81ff0b
Create Date: 2018-09-19 20:27:39.914130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245d116b8a06'
down_revision = 'f128dd81ff0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('cached_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'cached_path')
    # ### end Alembic commands ###
