"""remove cached bool

Revision ID: a23c7b701fb7
Revises: 245d116b8a06
Create Date: 2018-09-19 20:29:26.808322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23c7b701fb7'
down_revision = '245d116b8a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'cached')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('cached', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
