"""cached flag

Revision ID: f128dd81ff0b
Revises: 
Create Date: 2018-09-19 19:45:00.380030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f128dd81ff0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('cached', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'episode', ['id'])
    op.create_unique_constraint(None, 'podcast', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'podcast', type_='unique')
    op.drop_constraint(None, 'episode', type_='unique')
    op.drop_column('episode', 'cached')
    # ### end Alembic commands ###
